// Generated by `wrangler types`. Secrets are declared so local/CI typecheck
// does not depend on a populated `.dev.vars`.
declare namespace Cloudflare {
	interface Env {
		AI: Ai;
		VECTORIZE: Vectorize;
		MemoryAgent: DurableObjectNamespace<import("./src/agents/memory-agent").MemoryAgent>;
		SourceAgent: DurableObjectNamespace<import("./src/agents/source-agent").SourceAgent>;
		INGEST_WORKFLOW: Workflow<{
			userId: string;
			request: import("@yumeoi/domain").IngestRequest;
		}>;
		DOCS: R2Bucket;
		DB: D1Database;
		OAUTH_KV: KVNamespace;
		OAUTH_PROVIDER?: import("@cloudflare/workers-oauth-provider").OAuthHelpers;
		AI_GATEWAY_ID: string;
		OPENROUTER_API_KEY?: string;
		OPENAI_API_KEY?: string;
		YUMEOI_API_KEY?: string;
		YUMEOI_USER_ID?: string;
		TOKEN_ENCRYPTION_KEY?: string;
		NOTION_CLIENT_ID?: string;
		NOTION_CLIENT_SECRET?: string;
		NOTION_REDIRECT_URI?: string;
	}
}

interface Env extends Cloudflare.Env {}
