// Generated by `wrangler types`. Secrets are declared so local/CI typecheck
// does not depend on a populated `.dev.vars`.
declare namespace Cloudflare {
	interface Env {
		AI: Ai;
		VECTORIZE: Vectorize;
		MemoryAgent: DurableObjectNamespace<import("./src/agents/memory-agent").MemoryAgent>;
		AI_GATEWAY_ID: string;
		OPENAI_API_KEY?: string;
		OPENROUTER_API_KEY?: string;
	}
}

interface Env extends Cloudflare.Env {}
