// Generated by `wrangler types`. Secrets are declared so local/CI typecheck
// does not depend on a populated `.dev.vars`.
declare namespace Cloudflare {
	interface Env {
		AI: Ai;
		VECTORIZE: Vectorize;
		MemoryAgent: DurableObjectNamespace<import("./src/agents/memory-agent").MemoryAgent>;
		INGEST_WORKFLOW: Workflow<{
			userId: string;
			request: import("@yumeoi/domain").IngestRequest;
		}>;
		DOCS: R2Bucket;
		DB: D1Database;
		AI_GATEWAY_ID: string;
		OPENAI_API_KEY?: string;
		YUMEOI_API_KEY?: string;
		YUMEOI_USER_ID?: string;
	}
}

interface Env extends Cloudflare.Env {}
